In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pandas_profiling as pp


In [16]:
! pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip

     \ 34.6 MB 705 kB/s
     |████████████████████████████████| 10.1 MB 71 kB/s 
     |████████████████████████████████| 596 kB 57.4 MB/s 
     |████████████████████████████████| 102 kB 13.6 MB/s 
     |████████████████████████████████| 675 kB 64.9 MB/s 
     |████████████████████████████████| 4.7 MB 78.0 MB/s 
     |████████████████████████████████| 62 kB 1.0 MB/s 
     |████████████████████████████████| 812 kB 62.9 MB/s 
     |████████████████████████████████| 28.5 MB 50 kB/s 
  Created wheel for pandas-profiling: filename=pandas_profiling-3.1.1-py2.py3-none-any.whl size=261261 sha256=e45bb432814bfd12a13cd6915a5c6d9caaf3e012e1deb3a7da6138df74dca696
  Stored in directory: /tmp/pip-ephem-wheel-cache-cv43698y/wheels/cc/d5/09/083fb07c9363a2f45854b0e3a7de7d7c560f07da74b9e9769d
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27098 sha256=117837c10b9b1038622a1e142c01b28ccc2d5f550c4f178f8e67443cc7228bef
  Stored in directory: /root/.cache/pip/wheels/70/e1/52/5b14d2

In [10]:
df = pd.read_csv('/content/loan_train.csv', low_memory=False)


In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24999 entries, 0 to 24998
Columns: 111 entries, id to total_il_high_credit_limit
dtypes: float64(74), int64(13), object(24)
memory usage: 21.2+ MB


In [12]:
df.head()

id  member_id  ...  total_bc_limit  total_il_high_credit_limit
0   573354     737474  ...             NaN                         NaN
1   476321     603324  ...             NaN                         NaN
2   451484     556265  ...             NaN                         NaN
3  1018129    1246557  ...             NaN                         NaN
4   800018    1005270  ...             NaN                         NaN

[5 rows x 111 columns]

In [13]:
print(df.shape)

(24999, 111)


In [16]:
profile = pp.ProfileReport(df, title = 'Loan_dataset', html = {'style': {'full_width': True}})

In [17]:
profile.to_notebook_iframe()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
profile.to_file(output_file = 'Loan_dataset.html')

In [20]:
for col_names in df.columns:
  print()

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       ...
       'num_tl_90g_dpd_24m', 'num_tl_op_past_12m', 'pct_tl_nvr_dlq',
       'percent_bc_gt_75', 'pub_rec_bankruptcies', 'tax_liens',
       'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit'],
      dtype='object', length=111)

In [39]:
df_re = pd.read_csv('/content/loan_train.csv', low_memory=False)

In [40]:
df_re = df_re.drop(['id','member_id','pymnt_plan','url','initial_list_status','mths_since_last_major_derog','policy_code','application_type','annual_inc_joint','dti_joint','verification_status_joint','acc_now_delinq','tot_coll_amt','tot_cur_bal','open_acc_6m','open_il_6m','open_il_12m', 'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il','il_util',	'open_rv_12m','open_rv_24m','max_bal_bc','all_util','total_rev_hi_lim', 'inq_fi','total_cu_tl','inq_last_12m','acc_open_past_24mths','avg_cur_bal','bc_open_to_buy','bc_util','delinq_amnt','mo_sin_old_il_acct','mo_sin_old_rev_tl_op','mo_sin_rcnt_rev_tl_op','mo_sin_rcnt_tl','mort_acc','mths_since_recent_bc','mths_since_recent_bc_dlq', 'mths_since_recent_inq', 'mths_since_recent_revol_delinq', 'num_accts_ever_120_pd','num_actv_bc_tl', 'num_actv_rev_tl', 'num_bc_sats','num_bc_tl','num_il_tl','num_op_rev_tl','num_rev_accts','num_rev_tl_bal_gt_0',		'num_sats',	'num_tl_120dpd_2m','num_tl_30dpd','num_tl_90g_dpd_24m',	'num_tl_op_past_12m',	'pct_tl_nvr_dlq','percent_bc_gt_75','tot_hi_cred_lim','total_bal_ex_mort','total_bc_limit',	'total_il_high_credit_limit'], axis =1)

In [42]:
print(df_re.shape)

(24999, 48)


In [31]:
df_re['collections_12_mths_ex_med'].unique()

In [25]:
df_re['chargeoff_within_12_mths'].unique()

array([ 0., nan])

In [26]:
df_re['tax_liens'].unique()

array([ 0., nan])

In [43]:
df_re = df_re.drop(['collections_12_mths_ex_med','chargeoff_within_12_mths','tax_liens'], axis= 1)

In [45]:
df_re.shape

(24999, 45)

In [47]:
profile_re = pp.ProfileReport(df_re, title = 'Loan_dataset', html = {'style': {'full_width': True}})
profile_re.to_notebook_iframe()
profile_re.to_file(output_file = 'Loan_dataset_re.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

# Desc of attributes
##emp_title
Job title.

##emp_length 
Number of years in the job, rounded down. If longer than 10 years, then this is represented by the value 10.

##state
Two-letter state code.

##home_ownership
The ownership status of the applicant's residence.

##annual_income
Annual income.

##verified_income
Type of verification of the applicant's income.

##debt_to_income
Debt-to-income ratio.

##annual_income_joint
If this is a joint application, then the annual income of the two parties applying.

##verification_income_joint
Type of verification of the joint income.

##debt_to_income_joint
Debt-to-income ratio for the two parties.

##delinq_2y
Delinquencies on lines of credit in the last 2 years.

##months_since_last_delinq
Months since the last delinquency.

##earliest_credit_line
Year of the applicant's earliest line of credit

##inquiries_last_12m
Inquiries into the applicant's credit during the last 12 months.

##total_credit_lines
Total number of credit lines in this applicant's credit history.

##open_credit_lines
Number of currently open lines of credit.

##total_credit_limit
Total available credit, e.g. if only credit cards, then the total of all the credit limits. This excludes a mortgage.

##total_credit_utilized
Total credit balance, excluding a mortgage.

##num_collections_last_12m
Number of collections in the last 12 months. This excludes medical collections.

##num_historical_failed_to_pay
The number of derogatory public records, which roughly means the number of times the applicant failed to pay.

##months_since_90d_late
Months since the last time the applicant was 90 days late on a payment.

##current_accounts_delinq
Number of accounts where the applicant is currently delinquent.

##total_collection_amount_ever
The total amount that the applicant has had against them in collections.

##current_installment_accounts
Number of installment accounts, which are (roughly) accounts with a fixed payment amount and period. A typical example might be a 36-month car loan.

##accounts_opened_24m
Number of new lines of credit opened in the last 24 months.

##months_since_last_credit_inquiry
Number of months since the last credit inquiry on this applicant.

##num_satisfactory_accounts
Number of satisfactory accounts.

##num_accounts_120d_past_due
Number of current accounts that are 120 days past due.

##num_accounts_30d_past_due
Number of current accounts that are 30 days past due.

##num_active_debit_accounts
Number of currently active bank cards.

##total_debit_limit
Total of all bank card limits.

##num_total_cc_accounts
Total number of credit card accounts in the applicant's history.

##num_open_cc_accounts
Total number of currently open credit card accounts.

##num_cc_carrying_balance
Number of credit cards that are carrying a balance.

##num_mort_accounts
Number of mortgage accounts.

##account_never_delinq_percent
Percent of all lines of credit where the applicant was never delinquent.

##tax_liens
a numeric vector

##public_record_bankrupt
Number of bankruptcies listed in the public record for this applicant.

##loan_purpose
The category for the purpose of the loan.

##application_type
The type of application: either individual or joint.

##loan_amount
The amount of the loan the applicant received.

##term
The number of months of the loan the applicant received.

##interest_rate
Interest rate of the loan the applicant received.

##installment
Monthly payment for the loan the applicant received.

##grade
Grade associated with the loan.

##sub_grade
Detailed grade associated with the loan.

##issue_month
Month the loan was issued.

##loan_status
Status of the loan.

##initial_listing_status
Initial listing status of the loan. (I think this has to do with whether the lender provided the entire loan or if the loan is across multiple lenders.)

##disbursement_method
Dispersement method of the loan.

##balance
Current balance on the loan.

##paid_total
Total that has been paid on the loan by the applicant.

##paid_principal
The difference between the original loan amount and the current balance on the loan.

##paid_interest
The amount of interest paid so far by the applicant.

##paid_late_fees 
Late fees paid by the applicant.

In [ ]:
my_dataset = my_dataset.drop([‘url’],axis=1)
my_dataset = my_dataset.dropna(thresh=half_count,axis=1)


In [ ]:
X = my_dataset.iloc[:, :-1].values 
y = my_dataset.iloc[:, -1].values


In [ ]:
X

array([[476321, 603324, 15000, ..., nan, nan, nan],
       [451484, 556265, 2000, ..., nan, nan, nan],
       [1018129, 1246557, 35000, ..., nan, nan, nan],
       ...,
       [568459, 731299, 24000, ..., nan, nan, nan],
       [397594, 428786, 14000, ..., nan, nan, nan],
       [660367, 844601, 13400, ..., nan, nan, nan]], dtype=object)

In [ ]:
my_dataset.to_csv(“processed_data/cleaned_dataset.csv”,index=False)
